# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'Virginia' do
pod 'Alamofire', '~> 2.0'
end

target 'VirginiaTests' do

end

target 'VirginiaUITests' do

end

